name = "backend-timesheet"
main = "src/index.ts"
compatibility_date = "2025-04-10"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "user_management"
database_id = "001b6fea-19ce-4b4f-95f9-f50b480f5770"
preview_database_id = "placeholder-preview-id" 